# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-27 20:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pruebas', '0002_person'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='home_country',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='home_country', to='pruebas.Country'),
        ),
    ]
